name: HandyTalk
description: "HandyTalk is very helpful for deaf and mute peoples to understand anothers."
publish_to: "none"

version: 1.0.3

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  file_picker: ^5.0.0
  emoji_picker_flutter: ^1.0.0
  fl_chart: ^0.68.0
  speech_to_text: ^6.6.2
  permission_handler: ^11.3.1
  flutter_sound: ^9.8.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/page-circle-one.png
    - assets/images/3d-model.png
    - assets/images/language-chang-to-sinhala.png
    - assets/images/language-chang-to-english.png
    - assets/images/profile-picture-icon.png
    - assets/images/notification-icon-without-notification.png
    - assets/images/back-image.png
    - assets/images/add-new-message.png
    - assets/images/default-notification.png
    - assets/images/tempory_img.png
    - assets/images/page-circle-signin-username.png
    - assets/images/page-circle-signin-password.png
    - assets/icon/icon.png
    - assets/images/page-circle-two.png
    - assets/images/page-circle-signup-one.png
    - assets/images/page-circle-signup-two.png
    - assets/images/page-circle-signup-three.png
    - assets/images/page-circle-signup-four.png
    - assets/images/page-circle-signup-five.png
    - assets/images/page-circle-signup-six.png
    - assets/images/premium-pages.png
    - assets/images/sign_language.png
    - assets/images/alphabet.png
    - assets/images/numbers.png
    - assets/images/common_words.png
    - assets/images/game1.png
    - assets/images/game2.png
    - assets/images/game3.png
    - assets/images/game4.png
    - assets/images/face_image_1.png
    - assets/images/face_image_2.png
    - assets/images/shirt_01.png
    - assets/images/shirt_02.png
    - assets/images/shirt_03.png
    - assets/images/shirt_04.png
    - assets/images/shirt_05.png
    - assets/images/shirt_06.png
    - assets/images/NeuroTracker.png
    - assets/images/Cartoon_Vector.png
    - assets/images/Successful_Characters.png
    - assets/images/Select-all.png
    - assets/images/Fire.png
    - assets/images/Assignment-Return.png
    - assets/images/Check-All.png
    - assets/gif/
    - assets/gif/password.gif
    - assets/gif/address.gif
    - assets/gif/be_careful.gif
    - assets/gif/call_me.gif
    - assets/gif/can_you_help_me.gif
    - assets/gif/dont_like.gif
    - assets/gif/excuse_me.gif
    - assets/gif/good_bye.gif
    - assets/gif/good_job.gif
    - assets/gif/hello.gif
    - assets/gif/how_much.gif
    - assets/gif/i_am_hungry.gif
    - assets/gif/i_am_thirsty.gif
    - assets/gif/i_dont_understand.gif
    - assets/gif/like.gif
    - assets/gif/new.gif
    - assets/gif/next.gif
    - assets/gif/no.gif
    - assets/gif/please.gif
    - assets/gif/repeat.gif
    - assets/gif/reset.gif
    - assets/gif/see_you_late.gif
    - assets/gif/select.gif
    - assets/gif/take_care.gif
    - assets/gif/thank_you.gif
    - assets/gif/today.gif
    - assets/gif/wait.gif
    - assets/gif/what_time_is_it.gif
    - assets/gif/wrong.gif
    - assets/gif/yes.gif
    - assets/images/avatar_01.png
    - assets/images/avatar_02.png
    - assets/images/avatar_03.png
    - assets/images/avatar_04.png
    - assets/images/avatar_05.png


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Abhaya_Libre/AbhayaLibre-ExtraBold.ttf
        - asset: assets/fonts/Abhaya_Libre/AbhayaLibre-Medium.ttf
        - asset: assets/fonts/Abhaya_Libre/AbhayaLibre-Regular.ttf
        - asset: assets/fonts/Abhaya_Libre/AbhayaLibre-SemiBold.ttf
        - asset: assets/fonts/Abhaya_Libre/AbhayaLibre-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
