name: HandyTalk
description: "HandyTalk is very helpful for deaf and mute peoples to understand anothers."
publish_to: "none"

version: 1.0.2

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.4+1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/page-circle-one.png
    - assets/images/3d-model.png
    - assets/images/language-chang-to-sinhala.png
    - assets/images/language-chang-to-english.png
    - assets/images/profile-picture-icon.png
    - assets/images/notification-icon-without-notification.png
    - assets/images/back-image.png
    - assets/images/add-new-message.png
    - assets/images/default-notification.png
    - assets/images/tempory_img.png
    - assets/images/page-circle-signin-username.png
    - assets/images/page-circle-signin-password.png
    - assets/icon/icon.png
    - assets/images/page-circle-two.png
    - assets/images/page-circle-signup-one.png
    - assets/images/page-circle-signup-two.png
    - assets/images/page-circle-signup-three.png
    - assets/images/page-circle-signup-four.png
    - assets/images/page-circle-signup-five.png
    - assets/images/page-circle-signup-six.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Abhaya_Libre/AbhayaLibre-ExtraBold.ttf
        - asset: assets/fonts/Abhaya_Libre/AbhayaLibre-Medium.ttf
        - asset: assets/fonts/Abhaya_Libre/AbhayaLibre-Regular.ttf
        - asset: assets/fonts/Abhaya_Libre/AbhayaLibre-SemiBold.ttf
        - asset: assets/fonts/Abhaya_Libre/AbhayaLibre-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
