// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe888C36lmZbdG6sJ6ZRrqp6TURCmbnWs',
    appId: '1:756865579969:web:88eea77b2c89accc7c8d40',
    messagingSenderId: '756865579969',
    projectId: 'handytalk-8bb4e',
    authDomain: 'handytalk-8bb4e.firebaseapp.com',
    storageBucket: 'handytalk-8bb4e.appspot.com',
    measurementId: 'G-6P0SLB6SV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwBBeOx32GKV2qCaeSZF8v9s855oaIH2g',
    appId: '1:756865579969:android:88bd41d9128f56287c8d40',
    messagingSenderId: '756865579969',
    projectId: 'handytalk-8bb4e',
    storageBucket: 'handytalk-8bb4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUNyYebCGXe8YFCOFsDpuB8N0Cev-jj8Y',
    appId: '1:756865579969:ios:b5a0be0207fd330e7c8d40',
    messagingSenderId: '756865579969',
    projectId: 'handytalk-8bb4e',
    storageBucket: 'handytalk-8bb4e.appspot.com',
    iosBundleId: 'com.example.handyTalkApplication',
  );
}
